In [29]:
import pandas as pd

input_file = 'reviews_BlackOps7_first1000.csv'
df = pd.read_csv(input_file)
print(f"Loaded {len(df)} reviews from {input_file}")

Loaded 999 reviews from reviews_BlackOps7_first1000.csv

In [30]:
# Remove duplicate rows
before = len(df)
df = df.drop_duplicates()
print(f"Removed {before - len(df)} duplicates. {len(df)} rows remaining.")
display(df.head())

Removed 786 duplicates. 213 rows remaining.

,review,author_vote,other_votes,weighted_vote_score,review_date
0,This game is the worst call of duty I have eve...,0,1724,0.974877,2026-03-01
1,"1/10 - Absolute Trash, AI Slop from Activision...",0,1159,0.932631,2026-03-03
2,Game forces you to have Secure Boot and TPM 2....,0,558,0.927817,2026-05-08
3,"I was playing Battlefield 6, and after a few b...",0,481,0.909235,2026-03-21
4,Black Ops 7 is a reskin of Black Ops 6 with mo...,0,282,0.870369,2026-05-08

In [31]:
from textblob import TextBlob


# --------------------------
# Sentiment Analysis
# --------------------------

def get_sentiment(text):

    polarity = TextBlob(text).sentiment.polarity
    return polarity 

    '''
    if polarity > 0.1:
        return "Positive"

    elif polarity < -0.1:
        return "Negative"

    return "Neutral"
    '''

In [33]:

# --------------------------
# Categorization
# --------------------------
def categorize_review(review):

    usability_keywords = [
        "bug",
        "crash",
        "lag",
        "fps",
        "server",
        "performance",

        "glitch",
        "stutter",
        "freeze",
        "disconnect",
        "error",
        "broken",
        "unoptimized",
        "latency",
        "ping",
        "hitbox",
        "connection",
        "frame rate",
        "loading",
        "memory leak",
    ]

    mechanic_keywords = [
        "movement",
        "weapon",
        "perk",
        "battle pass",
        "matchmaking",

        "loadout",
        "killstreak",
        "scorestreak",
        "operator",
        "map",
        "game mode",
        "respawn",
        "spawn",
        "ability",
        "class",
        "gunplay",
        "ttk",
        "time to kill",
        "recoil",
        "aim assist",
        "multiplayer",
        "zombies",
        "campaign",
        "season",
    ]

    comparison_keywords = [
        "better than",
        "worse than",
        "compared to",
        "similar to",
        
        "just like",
        "same as",
        "feels like",
        "plays like",
        "reminds me of",
        "prefer",
        "used to",
        "previous",
        "original",
        "back in",
        "inferior to",
        "superior to",
        "rip off",
        "copy of",
        "old cod",
    ]

    # New categories based on look for categories AI analysis of full review file
    ai_content_keywords = [
        "slop",
        "ai generated",
        "ai slop",
        "no effort",
        "copy paste",
        "lazy",
        "generated content",
        "soulless",
        "cash grab",
    ]

    monetization_keywords = [
        "refund",
        "worth",
        "price",
        "sale",
        "buying",
        "paid",
        "microtransaction",
        "endgame",
        "season pass",
        "overpriced",
        "free to play",
        "cosmetic",
        "store",
        "bundle",
    ]

    story_keywords = [
        "campaign",
        "story",
        "single player",
        "solo",
        "narrative",
        "mission",
        "ending",
        "cutscene",
        "plot",
        "character",
    ]

    technical_requirements_keywords = [
        "secure boot",
        "tpm",
        "bios",
        "hardware",
        "anti-cheat",
        "ricochet",
        "kernel",
        "driver",
        "compatibility",
        "system requirement",
    ]

    sbmm_keywords = [
        "sbmm",
        "skill based",
        "lobbies",
        "lobby",
        "sweaty",
        "ranked",
        "casual",
        "matchmaking",
        "skill gap",
        "pub stomp",
    ]

    community_keywords = [
        "friends",
        "team",
        "squad",
        "banned",
        "toxic",
        "solo",
        "party",
        "coop",
        "co-op",
        "community",
        "chat",
        "voice",
        "grief",
    ]

    review_lower = review.lower()

    categories = []

    if any(word in review_lower for word in usability_keywords):
        categories.append("Usability Issues")

    if any(word in review_lower for word in mechanic_keywords):
        categories.append("New Mechanic Reception")

    if any(word in review_lower for word in comparison_keywords):
        categories.append("Competitive Analysis")

    if any(word in review_lower for word in ai_content_keywords):
        categories.append("AI-Generated Content Complaints")

    if any(word in review_lower for word in monetization_keywords):
        categories.append("Monetization & Value")

    if any(word in review_lower for word in story_keywords):
        categories.append("Story / Campaign")

    if any(word in review_lower for word in technical_requirements_keywords):
        categories.append("Technical Requirements")

    if any(word in review_lower for word in sbmm_keywords):
        categories.append("SBMM / Matchmaking Frustration")

    if any(word in review_lower for word in community_keywords):
        categories.append("Community & Social")

    if len(categories) == 0:
        categories.append("Game Reception")

    return categories

In [34]:
# Run sentiment analysis and categorization, then save to a new CSV
sentiments = []
categories = []

for r in df['review']:
    sentiments.append(get_sentiment(r))
    categories.append(', '.join(categorize_review(r)))

df['sentiment'] = sentiments
df['categories'] = categories

display(df)

,review,author_vote,other_votes,weighted_vote_score,review_date,sentiment,categories
0,This game is the worst call of duty I have eve...,0,1724,0.974877,2026-03-01,-0.200000,Monetization & Value
1,"1/10 - Absolute Trash, AI Slop from Activision...",0,1159,0.932631,2026-03-03,-0.096655,"Usability Issues, New Mechanic Reception, Comp..."
2,Game forces you to have Secure Boot and TPM 2....,0,558,0.927817,2026-05-08,-0.071769,"New Mechanic Reception, Monetization & Value, ..."
3,"I was playing Battlefield 6, and after a few b...",0,481,0.909235,2026-03-21,-0.055720,"Usability Issues, New Mechanic Reception, Comp..."
4,Black Ops 7 is a reskin of Black Ops 6 with mo...,0,282,0.870369,2026-05-08,-0.002778,"New Mechanic Reception, AI-Generated Content C..."
...,...,...,...,...,...,...,...
221,bought this game thinking was gon have fun. no...,0,39,0.687997,2026-02-12,0.150000,Monetization & Value
222,UPDATE: Im now at 63 hours played. Zombies is ...,0,62,0.687826,2025-11-14,-0.007823,"New Mechanic Reception, Competitive Analysis, ..."
224,Start game > update requires restart > start g...,0,51,0.685999,2025-12-18,-0.285714,"New Mechanic Reception, Monetization & Value, ..."
225,Multiplayer : Still no ban for the zen chronus...,0,54,0.684135,2025-11-23,-0.095222,"Usability Issues, New Mechanic Reception, Comp..."
226,This BO7 campaign is the worst thing to happen...,0,52,0.733382,2025-12-26,0.071250,"New Mechanic Reception, Story / Campaign"

In [35]:
# Add a boolean column for each possible category
all_categories = [
    "Usability Issues",
    "New Mechanic Reception",
    "Competitive Analysis",
    "AI-Generated Content Complaints",
    "Monetization & Value",
    "Story / Campaign",
    "Technical Requirements",
    "SBMM / Matchmaking Frustration",
    "Community & Social",
    "Game Reception",
]

for category in all_categories:
    col_name = category.replace(" ", "_").replace("/", "_").replace("&", "and").replace("-", "_")
    col_values = []
    for cat_list in df['categories']:
        col_values.append(category in cat_list)
    df[col_name] = col_values

display(df.head(20))

,review,author_vote,other_votes,weighted_vote_score,review_date,sentiment,categories,Usability_Issues,New_Mechanic_Reception,Competitive_Analysis,AI_Generated_Content_Complaints,Monetization_and_Value,Story___Campaign,Technical_Requirements,SBMM___Matchmaking_Frustration,Community_and_Social,Game_Reception
0,This game is the worst call of duty I have eve...,0,1724,0.974877,2026-03-01,-0.200000,Monetization & Value,False,False,False,False,True,False,False,False,False,False
1,"1/10 - Absolute Trash, AI Slop from Activision...",0,1159,0.932631,2026-03-03,-0.096655,"Usability Issues, New Mechanic Reception, Comp...",True,True,True,True,True,True,False,True,True,False
2,Game forces you to have Secure Boot and TPM 2....,0,558,0.927817,2026-05-08,-0.071769,"New Mechanic Reception, Monetization & Value, ...",False,True,False,False,True,True,True,False,True,False
3,"I was playing Battlefield 6, and after a few b...",0,481,0.909235,2026-03-21,-0.055720,"Usability Issues, New Mechanic Reception, Comp...",True,True,True,False,True,False,False,False,False,False
4,Black Ops 7 is a reskin of Black Ops 6 with mo...,0,282,0.870369,2026-05-08,-0.002778,"New Mechanic Reception, AI-Generated Content C...",False,True,False,True,True,False,False,False,False,False
5,For the zombies enjoyers out there. Always onl...,0,166,0.818673,2026-03-16,-0.067500,"Usability Issues, New Mechanic Reception, Stor...",True,True,False,False,False,True,False,False,True,False
6,"AI generated SLOP. No effort, almost everythin...",0,230,0.813288,2026-03-01,-0.140000,"New Mechanic Reception, AI-Generated Content C...",False,True,False,True,False,True,False,False,True,False
7,game is terrible that is all i have to say. li...,0,156,0.795581,2026-05-08,-0.433333,"Story / Campaign, Community & Social",False,False,False,False,False,True,False,False,True,False
8,Open playlist has reduced SBMM? Where? Why do ...,0,245,0.856749,2026-04-19,-0.002679,"Usability Issues, New Mechanic Reception, Stor...",True,True,False,False,False,True,False,True,False,False
9,This game has become a joke. Activision does n...,0,50,0.745440,2026-05-13,-0.038333,"Monetization & Value, Community & Social",False,False,False,False,True,False,False,False,True,False
10,"ABSOLUTELY NEGATIVE, After 6 months of playing...",0,47,0.737829,2026-06-11,-0.083333,New Mechanic Reception,False,True,False,False,False,False,False,False,False,False
11,absolute trash. gave the game a chance at rele...,0,96,0.719371,2026-03-02,-0.218929,"Competitive Analysis, Monetization & Value",False,False,True,False,True,False,False,False,False,False
12,Biggest pos company on the planet. Bought it. ...,0,47,0.690686,2026-04-05,-0.048148,"Usability Issues, Monetization & Value",True,False,False,False,True,False,False,False,False,False
13,Comm banned for two weeks because someone was ...,0,133,0.737038,2026-05-07,-0.200000,Community & Social,False,False,False,False,False,False,False,False,True,False
14,"Same old formulaic gameplay, labelled as a new...",0,58,0.682332,2026-03-23,-0.020698,Game Reception,False,False,False,False,False,False,False,False,False,True
15,"I loaded up the game, I instantly got, Your PC...",0,27,0.682198,2026-05-17,-0.142857,"New Mechanic Reception, Monetization & Value",False,True,False,False,True,False,False,False,False,False
16,"For a game developed by a Triple A studio, you...",0,20,0.672290,2026-05-18,-0.188218,"Usability Issues, New Mechanic Reception, Comp...",True,True,True,True,False,False,False,False,True,False
17,This might actually be the worst game I have e...,0,36,0.667723,2026-05-10,-0.225000,Monetization & Value,False,False,False,False,True,False,False,False,False,False
18,I grew up playing Call of Duty. My hours on th...,0,28,0.667404,2026-03-20,-0.070408,Competitive Analysis,False,False,True,False,False,False,False,False,False,False
19,cant play basically any multiplayer because i ...,0,23,0.643716,2026-06-12,0.256250,"New Mechanic Reception, Technical Requirements",False,True,False,False,False,False,True,False,False,False

In [36]:
analyzed_file = input_file.replace('.csv', '_analyzed.csv')

df.to_csv(analyzed_file, index=False)
print(f"Saved {len(df)} analyzed reviews to {analyzed_file}")
df[['review', 'sentiment', 'categories']].head()

Saved 213 analyzed reviews to reviews_BlackOps7_first1000_analyzed.csv

,review,sentiment,categories
0,This game is the worst call of duty I have eve...,-0.200000,Monetization & Value
1,"1/10 - Absolute Trash, AI Slop from Activision...",-0.096655,"Usability Issues, New Mechanic Reception, Comp..."
2,Game forces you to have Secure Boot and TPM 2....,-0.071769,"New Mechanic Reception, Monetization & Value, ..."
3,"I was playing Battlefield 6, and after a few b...",-0.055720,"Usability Issues, New Mechanic Reception, Comp..."
4,Black Ops 7 is a reskin of Black Ops 6 with mo...,-0.002778,"New Mechanic Reception, AI-Generated Content C..."

In [37]:
# Read the analyzed CSV back and convert categories from string to list
df_analyzed = pd.read_csv(analyzed_file)

# Convert the categories column from comma-separated string to list
categories_list = []
for cat_string in df_analyzed['categories']:
    cat_list = []
    for cat in cat_string.split(','):
        cat_list.append(cat.strip())
    categories_list.append(cat_list)

df_analyzed['categories'] = categories_list

print(f"Loaded {len(df_analyzed)} analyzed reviews")
print("\nFirst few rows with categories as lists:")
display(df_analyzed)

Loaded 213 analyzed reviews

First few rows with categories as lists:

,review,author_vote,other_votes,weighted_vote_score,review_date,sentiment,categories,Usability_Issues,New_Mechanic_Reception,Competitive_Analysis,AI_Generated_Content_Complaints,Monetization_and_Value,Story___Campaign,Technical_Requirements,SBMM___Matchmaking_Frustration,Community_and_Social,Game_Reception
0,This game is the worst call of duty I have eve...,0,1724,0.974877,2026-03-01,-0.200000,[Monetization & Value],False,False,False,False,True,False,False,False,False,False
1,"1/10 - Absolute Trash, AI Slop from Activision...",0,1159,0.932631,2026-03-03,-0.096655,"[Usability Issues, New Mechanic Reception, Com...",True,True,True,True,True,True,False,True,True,False
2,Game forces you to have Secure Boot and TPM 2....,0,558,0.927817,2026-05-08,-0.071769,"[New Mechanic Reception, Monetization & Value,...",False,True,False,False,True,True,True,False,True,False
3,"I was playing Battlefield 6, and after a few b...",0,481,0.909235,2026-03-21,-0.055720,"[Usability Issues, New Mechanic Reception, Com...",True,True,True,False,True,False,False,False,False,False
4,Black Ops 7 is a reskin of Black Ops 6 with mo...,0,282,0.870369,2026-05-08,-0.002778,"[New Mechanic Reception, AI-Generated Content ...",False,True,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,bought this game thinking was gon have fun. no...,0,39,0.687997,2026-02-12,0.150000,[Monetization & Value],False,False,False,False,True,False,False,False,False,False
209,UPDATE: Im now at 63 hours played. Zombies is ...,0,62,0.687826,2025-11-14,-0.007823,"[New Mechanic Reception, Competitive Analysis,...",False,True,True,False,True,True,False,False,True,False
210,Start game > update requires restart > start g...,0,51,0.685999,2025-12-18,-0.285714,"[New Mechanic Reception, Monetization & Value,...",False,True,False,False,True,True,False,True,False,False
211,Multiplayer : Still no ban for the zen chronus...,0,54,0.684135,2025-11-23,-0.095222,"[Usability Issues, New Mechanic Reception, Com...",True,True,True,False,True,True,False,False,True,False
212,This BO7 campaign is the worst thing to happen...,0,52,0.733382,2025-12-26,0.071250,"[New Mechanic Reception, Story / Campaign]",False,True,False,False,False,True,False,False,False,False

In [ ]:
# Analysis suggestions:
# What is the number of each of the categories used? (what is the most/least common category)